# Azure Kubernetes Service (AKS) Deployment Manifests
# Enterprise application workloads for DR orchestration

---
# Namespace for DR orchestrator components
apiVersion: v1
kind: Namespace
metadata:
  name: dr-orchestrator
  labels:
    name: dr-orchestrator
    environment: production
    compliance: soc2-type-ii
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "environment=production"

---
# Service Account for DR orchestrator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-orchestrator-sa
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: service-account
  annotations:
    azure.workload.identity/client-id: "your-managed-identity-client-id"
    azure.workload.identity/use: "true"

---
# ClusterRole for DR orchestrator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dr-orchestrator-role
  labels:
    app: dr-orchestrator
    component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# ClusterRoleBinding for DR orchestrator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dr-orchestrator-binding
  labels:
    app: dr-orchestrator
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dr-orchestrator-role
subjects:
- kind: ServiceAccount
  name: dr-orchestrator-sa
  namespace: dr-orchestrator

---
# ConfigMap for DR orchestrator configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: dr-orchestrator-config
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: config
data:
  config.yaml: |
    # DR Orchestrator Configuration for AKS
    azure:
      subscription_id: "your-azure-subscription-id"
      resource_group: "prod-dr-azure-rg"
      location: "East US 2"
      
      sql_managed_instance:
        name: "prod-dr-sql-mi-001"
        server: "prod-dr-sql-mi-001.database.windows.net"
        database: "EnterpriseProductionDB"
        port: 1433
        
      aks_cluster:
        name: "prod-dr-aks-cluster"
        resource_group: "prod-dr-azure-rg"
        node_resource_group: "MC_prod-dr-azure-rg_prod-dr-aks-cluster_eastus2"
        
    gcp:
      project_id: "enterprise-dr-orchestrator"
      region: "us-central1"
      zone: "us-central1-a"
      
      cloud_sql:
        instance_name: "prod-dr-cloud-sql"
        database: "enterprise_app_db"
        connection_name: "enterprise-dr-orchestrator:us-central1:prod-dr-cloud-sql"
        private_ip: "10.1.1.100"
        port: 5432
        
      gke_cluster:
        name: "prod-dr-gke-cluster"
        location: "us-central1"
        
    striim:
      cluster_url: "https://striim-lb.company.com"
      application_name: "AzureToGcpDrReplication"
      username: "striim-admin"
      
    monitoring:
      prometheus_url: "http://prometheus-server:9090"
      grafana_url: "http://grafana:3000"
      alert_manager_url: "http://alertmanager:9093"
      
    dr_settings:
      rto_target_seconds: 300  # 5 minutes
      rpo_target_seconds: 30   # 30 seconds
      health_check_interval: 30
      failover_timeout: 600
      
    business_hours:
      timezone: "America/New_York"
      start_hour: 6
      end_hour: 23
      
  logging.yaml: |
    version: 1
    formatters:
      default:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: default
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: default
        filename: /var/log/dr-orchestrator/orchestrator.log
        maxBytes: 10485760
        backupCount: 10
    loggers:
      dr_orchestrator:
        level: INFO
        handlers: [console, file]
        propagate: no
    root:
      level: INFO
      handlers: [console]

---
# Secret for DR orchestrator credentials
apiVersion: v1
kind: Secret
metadata:
  name: dr-orchestrator-secrets
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: secrets
type: Opaque
stringData:
  azure-client-secret: "${AZURE_CLIENT_SECRET}"
  azure-sql-password: "${AZURE_SQL_PASSWORD}"
  gcp-service-account-key: |
    ${GCP_SERVICE_ACCOUNT_KEY}
  gcp-cloud-sql-password: "${GCP_CLOUD_SQL_PASSWORD}"
  striim-password: "${STRIIM_PASSWORD}"

---
# Persistent Volume Claim for logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dr-orchestrator-logs-pvc
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 10Gi

---
# Deployment for DR orchestrator main service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-orchestrator-main
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: main
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: dr-orchestrator
      component: main
  template:
    metadata:
      labels:
        app: dr-orchestrator
        component: main
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: dr-orchestrator-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: dr-orchestrator
        image: your-registry.azurecr.io/dr-orchestrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 8443
          name: https-api
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: CLOUD_PROVIDER
          value: "azure"
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_PORT
          value: "8080"
        - name: API_PORT
          value: "8443"
        - name: CONFIG_PATH
          value: "/app/config/config.yaml"
        - name: SECRETS_PATH
          value: "/app/secrets"
        envFrom:
        - secretRef:
            name: dr-orchestrator-secrets
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        - name: logs
          mountPath: /var/log/dr-orchestrator
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: dr-orchestrator-config
      - name: secrets
        secret:
          secretName: dr-orchestrator-secrets
      - name: logs
        persistentVolumeClaim:
          claimName: dr-orchestrator-logs-pvc
      - name: tmp
        emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
        node.kubernetes.io/instance-type: Standard_D4s_v3
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - dr-orchestrator
              topologyKey: kubernetes.io/hostname

---
# Service for DR orchestrator
apiVersion: v1
kind: Service
metadata:
  name: dr-orchestrator-service
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: service
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https-api
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: dr-orchestrator
    component: main

---
# Deployment for health monitor service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-health-monitor
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: health-monitor
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dr-orchestrator
      component: health-monitor
  template:
    metadata:
      labels:
        app: dr-orchestrator
        component: health-monitor
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: dr-orchestrator-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: health-monitor
        image: your-registry.azurecr.io/dr-health-monitor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http-metrics
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: CLOUD_PROVIDER
          value: "azure"
        - name: LOG_LEVEL
          value: "INFO"
        - name: METRICS_PORT
          value: "8081"
        - name: CONFIG_PATH
          value: "/app/config/config.yaml"
        - name: CHECK_INTERVAL
          value: "30"
        envFrom:
        - secretRef:
            name: dr-orchestrator-secrets
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        - name: logs
          mountPath: /var/log/dr-orchestrator
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: dr-orchestrator-config
      - name: secrets
        secret:
          secretName: dr-orchestrator-secrets
      - name: logs
        persistentVolumeClaim:
          claimName: dr-orchestrator-logs-pvc
      - name: tmp
        emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux

---
# Service for health monitor
apiVersion: v1
kind: Service
metadata:
  name: dr-health-monitor-service
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: health-monitor-service
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: dr-orchestrator
    component: health-monitor

---
# CronJob for periodic DR tests
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dr-test-runner
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: test-runner
spec:
  schedule: "0 2 * * 0"  # Every Sunday at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dr-orchestrator
            component: test-runner
        spec:
          serviceAccountName: dr-orchestrator-sa
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
          containers:
          - name: dr-test-runner
            image: your-registry.azurecr.io/dr-test-runner:latest
            imagePullPolicy: Always
            env:
            - name: ENVIRONMENT
              value: "production"
            - name: TEST_TYPE
              value: "weekly"
            - name: LOG_LEVEL
              value: "INFO"
            - name: CONFIG_PATH
              value: "/app/config/config.yaml"
            envFrom:
            - secretRef:
                name: dr-orchestrator-secrets
            volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
            - name: test-results
              mountPath: /app/test-results
            - name: tmp
              mountPath: /tmp
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
          volumes:
          - name: config
            configMap:
              name: dr-orchestrator-config
          - name: secrets
            secret:
              secretName: dr-orchestrator-secrets
          - name: test-results
            emptyDir: {}
          - name: tmp
            emptyDir: {}

---
# HorizontalPodAutoscaler for main orchestrator
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dr-orchestrator-hpa
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dr-orchestrator-main
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

---
# PodDisruptionBudget for main orchestrator
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dr-orchestrator-pdb
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dr-orchestrator
      component: main

---
# NetworkPolicy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dr-orchestrator-netpol
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: network-policy
spec:
  podSelector:
    matchLabels:
      app: dr-orchestrator
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: istio-system
    - podSelector:
        matchLabels:
          app: dr-orchestrator
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
    - protocol: TCP
      port: 8443
  egress:
  - {}  # Allow all egress traffic for cloud API calls

---
# ServiceMonitor for Prometheus scraping
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dr-orchestrator-monitor
  namespace: dr-orchestrator
  labels:
    app: dr-orchestrator
    component: monitoring
spec:
  selector:
    matchLabels:
      app: dr-orchestrator
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
    honorLabels: true
